dist: xenial
language: scala
sudo: true
scala: 2.12.7
jdk:
  - openjdk8
branches:
  only:
    - main
script:
  - sbt coverage test
#  - sbt ++$TRAVIS_SCALA_VERSION compile
#  - sbt ++$TRAVIS_SCALA_VERSION test
#  - sbt ++$TRAVIS_SCALA_VERSION package

after_success:
  - sbt coverageReport coveralls


